-- PostgreSQL Version of createTable.sql

-- 1. PERSON base table
CREATE TABLE PERSON (
  ID INT NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  PhoneNum VARCHAR(15) NOT NULL,
  PRIMARY KEY (ID)
);

-- 2. MEDICAL_STAFF
CREATE TABLE MEDICAL_STAFF (
  ID INT NOT NULL, 
  Salary DECIMAL(10,2) NOT NULL CHECK (Salary > 0),
  Email VARCHAR(100) NOT NULL UNIQUE,
  HireDate DATE NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_staff_person FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

-- 3. DEPARTMENT
CREATE TABLE DEPARTMENT (
  DepID INT NOT NULL,
  PhoneNum VARCHAR(15) NOT NULL,
  NumOfBeds INT NOT NULL CHECK (NumOfBeds >= 0),
  PRIMARY KEY (DepID)
);

-- 4. SHIFT
CREATE TABLE SHIFT (
  Staff_ID INT NOT NULL,
  Shift_Date DATE NOT NULL,
  StartTime TIMESTAMP NOT NULL,
  EndTime TIMESTAMP NOT NULL,
  PRIMARY KEY (Staff_ID, Shift_Date, StartTime), 
  CONSTRAINT fk_shift_staff FOREIGN KEY (Staff_ID) REFERENCES MEDICAL_STAFF(ID)
);

-- 5. LAB
CREATE TABLE LAB (
  LabID INT NOT NULL,
  Lab_Name VARCHAR(100) NOT NULL,
  NumOfTechnicians INT DEFAULT 0 CHECK (NumOfTechnicians >= 0),
  PRIMARY KEY (LabID)
);

-- 6. PATIENT
CREATE TABLE PATIENT (
  ID INT NOT NULL,
  BirthDate DATE NOT NULL,
  BloodType VARCHAR(5) CHECK (BloodType IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  PRIMARY KEY (ID),
  CONSTRAINT fk_patient_person FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

-- 7. ATTENDING_DOCTOR
CREATE TABLE ATTENDING_DOCTOR (
  Doctor_ID INT NOT NULL,
  DepID INT NOT NULL,
  PRIMARY KEY (Doctor_ID),
  CONSTRAINT fk_doctor_staff FOREIGN KEY (Doctor_ID) REFERENCES MEDICAL_STAFF(ID),
  CONSTRAINT fk_doctor_dep FOREIGN KEY (DepID) REFERENCES DEPARTMENT(DepID)
);

-- 8. MEDICATION
CREATE TABLE MEDICATION (
  M_ID INT NOT NULL,
  M_Name VARCHAR(100) NOT NULL,
  Price DECIMAL(8,2) NOT NULL CHECK (Price >= 0),
  PRIMARY KEY (M_ID)
);

-- 9. TREATMENT (שנינו ל-TIMESTAMP כדי למנוע כפילויות באותו יום)
CREATE TABLE TREATMENT (
  Patient_ID INT NOT NULL,
  Doctor_ID INT NOT NULL,
  Treatment_Date TIMESTAMP NOT NULL,
  PRIMARY KEY (Patient_ID, Doctor_ID, Treatment_Date),
  CONSTRAINT fk_treat_patient FOREIGN KEY (Patient_ID) REFERENCES PATIENT(ID),
  CONSTRAINT fk_treat_doctor FOREIGN KEY (Doctor_ID) REFERENCES ATTENDING_DOCTOR(Doctor_ID)
);

-- 10. MEDICATIONS_GIVEN
CREATE TABLE MEDICATIONS_GIVEN (
  M_ID INT NOT NULL,
  Patient_ID INT NOT NULL,
  Doctor_ID INT NOT NULL,
  Treatment_Date TIMESTAMP NOT NULL,
  PRIMARY KEY (M_ID, Patient_ID, Doctor_ID, Treatment_Date),
  CONSTRAINT fk_given_med FOREIGN KEY (M_ID) REFERENCES MEDICATION(M_ID),
  CONSTRAINT fk_given_treat FOREIGN KEY (Patient_ID, Doctor_ID, Treatment_Date) REFERENCES TREATMENT(Patient_ID, Doctor_ID, Treatment_Date)
);

-- 11. NURSE
CREATE TABLE NURSE (
  Nurse_ID INT NOT NULL,
  ShiftType VARCHAR(20),
  Specialization VARCHAR(100),
  DepID INT NOT NULL,
  PRIMARY KEY (Nurse_ID),
  CONSTRAINT fk_nurse_staff FOREIGN KEY (Nurse_ID) REFERENCES MEDICAL_STAFF(ID),
  CONSTRAINT fk_nurse_dep FOREIGN KEY (DepID) REFERENCES DEPARTMENT(DepID)
);

-- 12. RESEARCHER
CREATE TABLE RESEARCHER (
  Researcher_ID INT NOT NULL,
  Research_Field VARCHAR(100),
  StartDate DATE NOT NULL,
  LabID INT NOT NULL,
  PRIMARY KEY (Researcher_ID),
  CONSTRAINT fk_researcher_staff FOREIGN KEY (Researcher_ID) REFERENCES MEDICAL_STAFF(ID),
  CONSTRAINT fk_researcher_lab FOREIGN KEY (LabID) REFERENCES LAB(LabID)
);