-- person base table
CREATE TABLE PERSON (
  ID INT NOT NULL,
  FirstName VARCHAR2(50) NOT NULL,
  LastName VARCHAR2(50) NOT NULL,
  PhoneNum VARCHAR2(15) NOT NULL,
  PRIMARY KEY (ID)
);

-- medical_staff -> patient, nurse, researcher
CREATE TABLE MEDICAL_STAFF (
  ID INT NOT NULL, 
  Salary NUMERIC(10,2) NOT NULL CHECK (Salary > 0),
  Email VARCHAR2(100) NOT NULL UNIQUE,
  HireDate DATE NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE DEPARTMENT (
  DepID INT NOT NULL,
  PhoneNum VARCHAR2(15) NOT NULL,
  NumOfBeds INT NOT NULL CHECK (NumOfBeds >= 0),
  PRIMARY KEY (DepID)
);

CREATE TABLE SHIFT (
  Staff_ID INT NOT NULL,
  Shift_Date DATE NOT NULL,
  StartTime TIMESTAMP NOT NULL,
  EndTime TIMESTAMP NOT NULL,
  PRIMARY KEY (Staff_ID, Shift_Date, StartTime), 
  FOREIGN KEY (Staff_ID) REFERENCES MEDICAL_STAFF(ID)
);

CREATE TABLE LAB (
  LabID INT NOT NULL,
  Lab_Name VARCHAR2(100) NOT NULL,
  NumOfTechnicians INT DEFAULT 0 CHECK (NumOfTechnicians >= 0),
  PRIMARY KEY (LabID)
);

CREATE TABLE PATIENT (
  ID INT NOT NULL,
  BirthDate DATE NOT NULL,
  BloodType VARCHAR2(5) CHECK (BloodType IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE ATTENDING_DOCTOR (
  Doctor_ID INT NOT NULL,
  DepID INT NOT NULL,
  PRIMARY KEY (Doctor_ID),
  FOREIGN KEY (Doctor_ID) REFERENCES MEDICAL_STAFF(ID),
  FOREIGN KEY (DepID) REFERENCES DEPARTMENT(DepID)
);

CREATE TABLE MEDICATION (
  M_ID INT NOT NULL,
  M_Name VARCHAR2(100) NOT NULL,
  Price NUMERIC(8,2) NOT NULL CHECK (Price >= 0),
  PRIMARY KEY (M_ID)
);

CREATE TABLE TREATMENT (
  Patient_ID INT NOT NULL,
  Doctor_ID INT NOT NULL,
  Treatment_Date DATE NOT NULL,
  PRIMARY KEY (Patient_ID, Doctor_ID, Treatment_Date),
  FOREIGN KEY (Patient_ID) REFERENCES PATIENT(ID),
  FOREIGN KEY (Doctor_ID) REFERENCES ATTENDING_DOCTOR(Doctor_ID)
);

-- many to many relationship between TREATMENT and MEDICATION
CREATE TABLE MEDICATIONS_GIVEN (
  M_ID INT NOT NULL,
  Patient_ID INT NOT NULL,
  Doctor_ID INT NOT NULL,
  Treatment_Date DATE NOT NULL,
  PRIMARY KEY (M_ID, Patient_ID, Doctor_ID, Treatment_Date),
  FOREIGN KEY (M_ID) REFERENCES MEDICATION(M_ID),
  FOREIGN KEY (Patient_ID, Doctor_ID, Treatment_Date) REFERENCES TREATMENT(Patient_ID, Doctor_ID, Treatment_Date)
);

CREATE TABLE NURSE (
  Nurse_ID INT NOT NULL,
  ShiftType VARCHAR2(20),
  Specialization VARCHAR2(100),
  DepID INT NOT NULL,
  PRIMARY KEY (Nurse_ID),
  FOREIGN KEY (Nurse_ID) REFERENCES MEDICAL_STAFF(ID),
  FOREIGN KEY (DepID) REFERENCES DEPARTMENT(DepID)
);

CREATE TABLE RESEARCHER (
  Researcher_ID INT NOT NULL,
  Research_Field VARCHAR2(100),
  StartDate DATE NOT NULL,
  LabID INT NOT NULL,
  PRIMARY KEY (Researcher_ID),
  FOREIGN KEY (Researcher_ID) REFERENCES MEDICAL_STAFF(ID),
  FOREIGN KEY (LabID) REFERENCES LAB(LabID)
);
