-- first drop tables with foreign keys
DROP TABLE IF EXISTS MEDICATIONS_GIVEN CASCADE;
DROP TABLE IF EXISTS TREATMENT CASCADE;
DROP TABLE IF EXISTS SHIFT CASCADE;
DROP TABLE IF EXISTS NURSE CASCADE;
DROP TABLE IF EXISTS RESEARCHER CASCADE;
DROP TABLE IF EXISTS ATTENDING_DOCTOR CASCADE;

-- next drop tables without foreign keys
DROP TABLE IF EXISTS MEDICAL_STAFF CASCADE;
DROP TABLE IF EXISTS PATIENT CASCADE;
DROP TABLE IF EXISTS MEDICATION CASCADE;
DROP TABLE IF EXISTS LAB CASCADE;
DROP TABLE IF EXISTS DEPARTMENT CASCADE;
DROP TABLE IF EXISTS PERSON CASCADE;