-- =============================================================
-- insertTables.sql
-- Master script for populating all tables with data.
-- Data is inserted using 3 different methods:
-- =============================================================

-- =============================================================
-- METHOD 1: CSV Import (DataImportFiles/)
-- Tables: PERSON (21,500 records), PATIENT (20,000 records)
--
-- CSV files were generated using a Python script (generate_csv.py).
-- Import is done via SQL*Loader with the following commands:
--
--   sqlldr userid=<user>/<pass>@<sid> control=person.ctl skip=1
--   sqlldr userid=<user>/<pass>@<sid> control=patient.ctl skip=1
--
-- Control files: person.ctl, patient.ctl
-- Data files: person.csv, patient.csv
-- =============================================================


-- =============================================================
-- METHOD 2: Python-generated INSERT statements (Programing/)
-- Tables: MEDICAL_STAFF (1,500), ATTENDING_DOCTOR (500),
--         NURSE (500), RESEARCHER (500), SHIFT (500),
--         TREATMENT (20,000), MEDICATIONS_GIVEN (500)
--
-- Generated by: generate_inserts.py
-- Output file:  generated_inserts.sql
-- Run with:     @Programing/generated_inserts.sql
-- =============================================================
@../Programing/generated_inserts.sql


-- =============================================================
-- METHOD 3: generatedata-style INSERT statements (generatedataFiles/)
-- Tables: DEPARTMENT (500), LAB (500), MEDICATION (500)
--
-- Generated by: generate_data.py
-- Output file:  insert_tables.sql
-- Run with:     @generatedataFiles/insert_tables.sql
-- =============================================================
@../generatedataFiles/insert_tables.sql


COMMIT;
