-- Select all data from all tables

PROMPT === PERSON ===
SELECT * FROM PERSON;

PROMPT === MEDICAL_STAFF ===
SELECT * FROM MEDICAL_STAFF;

PROMPT === DEPARTMENT ===
SELECT * FROM DEPARTMENT;

PROMPT === LAB ===
SELECT * FROM LAB;

PROMPT === PATIENT ===
SELECT * FROM PATIENT;

PROMPT === ATTENDING_DOCTOR ===
SELECT * FROM ATTENDING_DOCTOR;

PROMPT === NURSE ===
SELECT * FROM NURSE;

PROMPT === RESEARCHER ===
SELECT * FROM RESEARCHER;

PROMPT === MEDICATION ===
SELECT * FROM MEDICATION;

PROMPT === SHIFT ===
SELECT * FROM SHIFT;

PROMPT === TREATMENT ===
SELECT * FROM TREATMENT;

PROMPT === MEDICATIONS_GIVEN ===
SELECT * FROM MEDICATIONS_GIVEN;

-- Record counts summary
PROMPT === RECORD COUNTS ===
SELECT 'PERSON' AS Table_Name, COUNT(*) AS Record_Count FROM PERSON
UNION ALL SELECT 'MEDICAL_STAFF', COUNT(*) FROM MEDICAL_STAFF
UNION ALL SELECT 'DEPARTMENT', COUNT(*) FROM DEPARTMENT
UNION ALL SELECT 'LAB', COUNT(*) FROM LAB
UNION ALL SELECT 'PATIENT', COUNT(*) FROM PATIENT
UNION ALL SELECT 'ATTENDING_DOCTOR', COUNT(*) FROM ATTENDING_DOCTOR
UNION ALL SELECT 'NURSE', COUNT(*) FROM NURSE
UNION ALL SELECT 'RESEARCHER', COUNT(*) FROM RESEARCHER
UNION ALL SELECT 'MEDICATION', COUNT(*) FROM MEDICATION
UNION ALL SELECT 'SHIFT', COUNT(*) FROM SHIFT
UNION ALL SELECT 'TREATMENT', COUNT(*) FROM TREATMENT
UNION ALL SELECT 'MEDICATIONS_GIVEN', COUNT(*) FROM MEDICATIONS_GIVEN;
