SELECT 'PERSON' as table, count(*) FROM PERSON
UNION ALL SELECT 'PATIENT', count(*) FROM PATIENT
UNION ALL SELECT 'TREATMENT', count(*) FROM TREATMENT
UNION ALL SELECT 'MEDICAL_STAFF', count(*) FROM MEDICAL_STAFF
UNION ALL SELECT 'NURSE', count(*) FROM NURSE
UNION ALL SELECT 'DOCTORS', count(*) FROM ATTENDING_DOCTOR;