PROMPT --- Counting Records ---
SELECT 'PERSON' as Table_Name, COUNT(*) FROM PERSON
UNION ALL SELECT 'PATIENT', COUNT(*) FROM PATIENT
UNION ALL SELECT 'MEDICAL_STAFF', COUNT(*) FROM MEDICAL_STAFF
UNION ALL SELECT 'DEPARTMENT', COUNT(*) FROM DEPARTMENT
UNION ALL SELECT 'TREATMENT', COUNT(*) FROM TREATMENT
UNION ALL SELECT 'MEDICATIONS_GIVEN', COUNT(*) FROM MEDICATIONS_GIVEN;

PROMPT --- Sampling Data ---
SELECT * FROM PERSON FETCH FIRST 10 ROWS ONLY;
SELECT * FROM MEDICAL_STAFF FETCH FIRST 10 ROWS ONLY;
SELECT * FROM TREATMENT FETCH FIRST 10 ROWS ONLY;